title: Continuous architecture
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "continuous-architecture.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

asciidoctor:
  base_dir: :source
  attributes:
    - icons=font
    
algolia:
  application_id: CA_WebSite
  index_name: jekyll
  search_only_api_key: 96a98d738921aee297c35e182f52ce2f 
  
keep_files:
  - docs

plugins:
  - jekyll-postcss

postcss:
  cache: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
