name: Build Asciidoc, Jekyll then Upload to S3

on: [push]

jobs:
  asciidoc-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: copy image files
        run: |
          mkdir -p ./dist/docs
          find docs -iname '*.jpg' -exec cp --parents {} ./dist/docs/ \;
          find docs -iname '*.png' -exec cp --parents {} ./dist/docs/ \;
          ls ./dist/docs/
        working-directory: .
      - name: Asciidoctor HTML build 
        id: asciidoc-html-build
        uses: avattathil/asciidoctor-action@master
        with:
             program: "asciidoctor -D dist/docs docs/index.adoc"
      - name: Asciidoctor PDF build 
        id: asciidoc-pdf-build
        uses: avattathil/asciidoctor-action@master
        with:
             program: "asciidoctor-pdf --out-file dist/docs/continuous-architecture.pdf docs/index.adoc"
      - name: List generated files
        run: 
          find ./dist/docs
        working-directory: .
      - name: Copy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist/docs'
          destination_dir: 'docs'
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Jekyll build
        id: jekyll-build
        uses: helaili/jekyll-action@v2
        with:
          target_path: dist 
          build_onlu: true
          jekyll_src: landing
      - name: List generated files
        run: 
          find ./dist
        working-directory: .
      - name: Copy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist'
          destination_dir: ''

