name: Build Landing Page with Jekyll then Upload to S3

on:
  push:
    paths:
    - 'landing/**'
  workflow_dispatch:

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create dist directory
        run:
          mkdir -p ./dist
      - name: Jekyll build
        id: jekyll-build
        uses: helaili/jekyll-action@v2
        with:
          jekyll_build_options: --destination ../dist
          build_only: true
          jekyll_src: landing
      - name: List generated files
        run: 
          find ./dist
        working-directory: .
      - name: Copy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist'
          destination_dir: ''
      - name: Invalidate Cloudfront distribution
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/**'
          AWS_REGION: 'eu-west-3'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
