name: Upload to S3

on: [push]

jobs:
  cp-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: copy image files
        run: |
          find docs -iname '*.jpg' -exec cp {} ./output/img \;
          find docs -iname '*.png' -exec cp {} ./output/img \;
          ls ./output/img
        working-directory: .
      - name: asciidoctor generation
        id: adocbuild
        uses: avattathil/asciidoctor-action@master
        with:
             program: "asciidoctor -R docs -D output **/*.adoc"
      - name: copy image files
        run: 
          find output -iname '*.html'
        working-directory: .
      - name: list generated files
        run: 
          find ./output
        working-directory: .
      - name: copy to s3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'output'
          destination_dir: '.'