name: Upload to S3

on: [push]

jobs:
  cp-images:
    runs-on: ubuntu-latest
    steps:
      - name: copy image files
        run: find . -type f -name '*.png' -o -name '*.jpg' -exec cp {} /output/img \;
        working-directory: .
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'img'
          destination_dir: 'docs'
